merged in v131

diff --git a/support/build/php b/support/build/php
--- a/support/build/php
+++ b/support/build/php
@@ -18,14 +18,18 @@ dep_dirname=php-${dep_version}
 dep_archive_name=${dep_dirname}.tar.gz
 if [[ $dep_version == *alpha* ]] || [[ $dep_version == *beta* ]] || [[ $dep_version == *RC* ]]; then
     if [[ $dep_version == 5.5.* ]]; then
-        dep_url=http://downloads.php.net/~jpauli/${dep_archive_name}
+        dep_url=https://downloads.php.net/~jpauli/${dep_archive_name}
     elif [[ $dep_version == 5.6.* ]]; then
-        dep_url=http://downloads.php.net/~tyrael/${dep_archive_name}
+        dep_url=https://downloads.php.net/~tyrael/${dep_archive_name}
     elif [[ $dep_version == 7.0.* ]]; then
         dep_url=https://downloads.php.net/~ab/${dep_archive_name}
+    elif [[ $dep_version == 7.1.* ]]; then
+        dep_url=https://downloads.php.net/~krakjoe/${dep_archive_name}
+    elif [[ $dep_version == 7.2.* ]]; then
+        dep_url=https://downloads.php.net/~pollita/${dep_archive_name}
     fi
 else
-    dep_url=http://us1.php.net/get/${dep_archive_name}/from/this/mirror
+    dep_url=https://php.net/get/${dep_archive_name}/from/this/mirror
 fi
 dep_manifest=${dep_package}.composer.json
 
@@ -35,28 +39,81 @@ curl -L ${dep_url} | tar xz
 
 pushd ${dep_dirname}
 
-apt-get update || { echo "Failed to 'apt-get update'. You must build this formula using Docker."; exit 1; }
-# we need libgmp-dev for GMP, libpam0g-dev for IMAP, libicu-dev for intl, libsasl2-dev for LDAP
-apt-get install -y libgmp-dev libpam0g-dev libicu-dev libsasl2-dev
+libicu="libicu55"
+if [[ $STACK == "cedar-14" ]]; then
+    libicu="libicu52"
+fi
+# we need libgmp for GMP, libpam0g for IMAP, libicu for intl, libsasl2/krb/ldap for LDAP
+needed=( libgmp10 libpam0g $libicu libsasl2-2 libkrb5-3 libldap-2.4-2 )
+if [[ $STACK != "cedar-14" ]]; then
+    needed+=( libsodium18 )
+fi
+missing=$(comm -1 -3 <(dpkg-query -W -f '${package}\n' | sort) <(IFS=$'\n'; echo "${needed[*]}" | sort))
+if [[ "$missing" ]]; then
+    echo "Error! Missing libraries: $missing"
+    exit 1
+fi
+# we need libgmp-dev for GMP, libpam0g-dev for IMAP, libicu-dev for intl, libsasl2/krb5/ldap2-dev for LDAP
+needed=( libgmp-dev libpam0g-dev libicu-dev libsasl2-dev libkrb5-dev libldap2-dev )
+if [[ $STACK != "cedar-14" ]]; then
+    needed+=( libsodium-dev )
+fi
+missing=$(comm -1 -3 <(dpkg-query -W -f '${package}\n' | sort) <(IFS=$'\n'; echo "${needed[*]}" | sort))
+if [[ "$missing" ]]; then
+    apt-get update -qq || { echo "Failed to 'apt-get update'. You must build this formula using Docker."; exit 1; }
+    apt-get install -q -y $missing
+fi
 
-# look for GMP libs in /usr/lib/x86_64-linux-gnu and not /usr/lib
-sed -i 's/$GMP_DIR\/$PHP_LIBDIR/$GMP_DIR\/$PHP_LIBDIR\/x86_64-linux-gnu/' configure
-# symlink in gmp.h
-ln -s /usr/include/x86_64-linux-gnu/gmp.h /usr/include/gmp.h
+if dpkg --compare-versions "$dep_version" "lt" 7.0.16 || dpkg --compare-versions "$dep_version" "eq" 7.1.0 || dpkg --compare-versions "$dep_version" "eq" 7.1.1; then
+    # look for GMP libs in /usr/lib/x86_64-linux-gnu and not /usr/lib
+    sed -i 's/$GMP_DIR\/$PHP_LIBDIR/$GMP_DIR\/$PHP_LIBDIR\/x86_64-linux-gnu/' configure
+    # symlink in gmp.h
+    ln -s /usr/include/x86_64-linux-gnu/gmp.h /usr/include/gmp.h
+fi
 
-# look for LDAP and SASL libs in /usr/lib/x86_64-linux-gnu and not /usr/lib
-sed -i 's/LDAP_LIBDIR=$i\/$PHP_LIBDIR/LDAP_LIBDIR=$i\/$PHP_LIBDIR\/x86_64-linux-gnu/' configure
-sed -i 's/LDAP_SASL_LIBDIR=$LDAP_SASL_DIR\/$PHP_LIBDIR/LDAP_SASL_LIBDIR=$LDAP_SASL_DIR\/$PHP_LIBDIR\/x86_64-linux-gnu/' configure
+if dpkg --compare-versions "$dep_version" "lt" 7.1.15 || dpkg --compare-versions "$dep_version" "eq" 7.2.0 || dpkg --compare-versions "$dep_version" "eq" 7.2.1 || dpkg --compare-versions "$dep_version" "eq" 7.2.2; then
+    # look for LDAP and SASL libs in /usr/lib/x86_64-linux-gnu and not /usr/lib
+    sed -i 's/LDAP_LIBDIR=$i\/$PHP_LIBDIR/LDAP_LIBDIR=$i\/$PHP_LIBDIR\/x86_64-linux-gnu/' configure
+    sed -i 's/LDAP_SASL_LIBDIR=$LDAP_SASL_DIR\/$PHP_LIBDIR/LDAP_SASL_LIBDIR=$LDAP_SASL_DIR\/$PHP_LIBDIR\/x86_64-linux-gnu/' configure
+fi
+
+# let's see if mcrypt is there, if not then we have to use the vendored one
+needed=( libmcrypt4 )
+missing=$(comm -1 -3 <(dpkg-query -W -f '${package}\n' | sort) <(IFS=$'\n'; echo "${needed[*]}" | sort))
+if [[ "$missing" ]]; then
+    echo "Using vendored libmcrypt..."
+    # use vendored libmcrypt
+    mcrypt_prefix="${OUT_PREFIX}"
+else
+    echo "Using system libmcrypt..."
+    # use system libmcrypt
+    mcrypt_prefix=
+    # but do we need headers?
+    needed=( libmcrypt-dev )
+    missing=$(comm -1 -3 <(dpkg-query -W -f '${package}\n' | sort) <(IFS=$'\n'; echo "${needed[*]}" | sort))
+    if [[ "$missing" ]]; then
+        apt-get update -qq || { echo "Failed to 'apt-get update'. You must build this formula using Docker."; exit 1; }
+        apt-get install -q -y $missing
+    fi
+fi
 
 configureopts=
 if [[ $dep_version == 7.* ]]; then
     configureopts="\
---with-mcrypt=shared,${OUT_PREFIX} \
 --enable-opcache-file\
 "
+    if [[ $dep_version == 7.0.* || $dep_version == 7.1.* ]]; then
+        configureopts="\
+--with-mcrypt=shared${mcrypt_prefix:+","}${mcrypt_prefix} \
+"
+    elif [[ $STACK != "cedar-14" ]]; then
+        configureopts="\
+--with-sodium=shared \
+"
+    fi
 else
     configureopts="\
---with-mcrypt=${OUT_PREFIX} \
+--with-mcrypt${mcrypt_prefix:+"="}${mcrypt_prefix} \
 --with-mysql=shared \
 "
 fi
@@ -87,11 +144,10 @@ export PATH=${OUT_PREFIX}/bin:$PATH
     --enable-exif=shared \
     --enable-ftp=shared \
     --with-gd=shared \
-        --enable-gd-native-ttf \
         --with-freetype-dir=/usr \
         --with-jpeg-dir=/usr \
         --with-png-dir=/usr \
-    --with-gettext=shared,${OUT_PREFIX} \
+    --with-gettext=shared \
     --with-gmp=shared \
     --with-imap=shared,${OUT_PREFIX}/opt/imap-2007f \
         --with-imap-ssl \
@@ -138,8 +194,9 @@ extra=$(echo "${shared[@]}" | python -c 'import sys, json; json.dump({"shared": 
 
 MANIFEST_REQUIRE="${MANIFEST_REQUIRE:-"{}"}"
 MANIFEST_CONFLICT="${MANIFEST_CONFLICT:-"{\"heroku-sys/hhvm\":\"*\"}"}"
-MANIFEST_EXTRA="${MANIFEST_EXTRA:-"$extra"}"
 MANIFEST_REPLACE=$(php composer.phar show --platform | grep -E '^(ext-\S+|php-64bit\b|hhvm\b)' | tr -s " " | cut -d " " -f1,2 | sed -e "s/ $dep_version\$/ self.version/" -e 's/^/heroku-sys\//' | python -c 'import sys, json; json.dump(dict(item.split() for item in sys.stdin), sys.stdout)')
+MANIFEST_PROVIDE="${MANIFEST_PROVIDE:-"{}"}"
+MANIFEST_EXTRA="${MANIFEST_EXTRA:-"$extra"}"
 
 # remove temporary ini file that enables all extensions, and the composer download
 rm ${OUT_PREFIX}/etc/php/php.ini composer.phar
@@ -157,6 +214,6 @@ cat > ${OUT_PREFIX}/bin/profile.php.sh <<'EOF'
 export PATH="$HOME/.heroku/php/bin:$HOME/.heroku/php/sbin:$PATH"
 EOF
 
-python $(dirname $BASH_SOURCE)/_util/include/manifest.py "heroku-sys-php" "heroku-sys/${dep_name}" "$dep_version" "${dep_formula}.tar.gz" "$MANIFEST_REQUIRE" "$MANIFEST_CONFLICT" "$MANIFEST_REPLACE" "$MANIFEST_EXTRA" > $dep_manifest
+python $(dirname $BASH_SOURCE)/_util/include/manifest.py "heroku-sys-php" "heroku-sys/${dep_name}" "$dep_version" "${dep_formula}.tar.gz" "$MANIFEST_REQUIRE" "$MANIFEST_CONFLICT" "$MANIFEST_REPLACE" "$MANIFEST_PROVIDE" "$MANIFEST_EXTRA" > $dep_manifest
 
 print_or_export_manifest_cmd "$(generate_manifest_cmd "$dep_manifest")"
